// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqwpepfvlbvtsmaicorv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxd3BlcGZ2bGJ2dHNtYWljb3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTAwMTcsImV4cCI6MjA1NjQ4NjAxN30.KKho_ZunrC_6kXI2YCKR-NsatYLvl8SJTyhvnoDUR7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);